package oa

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	OaTeachersRouter
	OaAppraisalRouter
	OaWorksRouter
	OaSalaryRouter
	OaAttendanceRouter
	OaClassHourRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
