package oa

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	OaTeachersApi
	OaAppraisalApi
	OaWorksApi
	OaAttendanceApi
	OaSalaryApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
